### ISSUE TITLE
new feature: promote/demote bookmark

### ISSUE THREAD

**Issue by Adam-it** [estruyf/vscode-squarl#2]
## 🎯 Aim

The aim of this issue is add a new feature that will allow to:
- promote: should only appear for project bookmarks, so they become global bookmarks
- demote: should only appear for global bookmarks, so they can be put on the local level

## ❗Remarks

While promoting or demoting (moving) we should allow the user to pick a group

## 📷 Mocked result

![image](https://user-images.githubusercontent.com/58668583/191358643-85c625ef-6f04-43ea-a9bd-77eb7e892d0b.png)

## ✅ ToDo

- [ ] Add promote link
- [ ] Add demote link
- [ ] Add possibility to pick group

**Comment by Adam-it** [comment]
please assign me to this one 👍
